version: '3.8'


services:
    # Application Service
    app:
        container_name: laravel
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www
        depends_on:
            - db


    # Database Service
    db:
        image: postgres:16.0
        container_name: postgres
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: crud_app
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Bakchlamo@@12345


    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "14200:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db


    # pgAdmin Service
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        ports:
            - "5050:80"
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: prasunamudawari@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
