version: '3'

services:
    php-fpm:
        build:
            context: .  # Chemin du contexte de build
            dockerfile: Dockerfile  # Chemin du Dockerfile
        volumes:
            - ./:/var/www/html  # Utilisation du chemin absolu du répertoire racine du projet

    nginx:
        image: nginx:latest
        ports:
            - "14200:80"
        volumes:
            - ./nginx/config.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html  # Utilisation du chemin absolu du répertoire racine du projet
        depends_on:
            - php-fpm

#    postgresql:
#        image: postgres:latest
#        container_name: laravel_postgresql
#        ports:
#            - "14432:5432"
#        environment:
#            POSTGRES_USER: postgres
#            POSTGRES_PASSWORD: arnoldetmaX2912
#            POSTGRES_DB: Crud
#        volumes:
#            - postgresql_data:/var/lib/postgresql/data
#        networks:
#            - laravel-network

        #postgres:
        #container_name: postgres_hire
        #image: "postgres:13.8-alpine"
            #volumes:
            #- pgsql_data:/var/lib/postgresql/data
            #environment:
            #POSTGRES_PASSWORD: secret
            #POSTGRES_USER: core_user
            #POSTGRES_DB: test_company_db
            #POSTGRES_INITDB_ARGS: "--encoding=UTF8"
        #restart: unless-stopped
            #ports:
            #- "14432:5432"
    #volumes:
    #pgsql_data:



    postgres:
        container_name: postgres_hire
        image: "postgres:13.8-alpine"
        volumes:
            - pgsql_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: arnoldetmaX291
            POSTGRES_USER: postgres
            POSTGRES_DB: Crud
            POSTGRES_INITDB_ARGS: "--encoding=UTF8"
        restart: unless-stopped
        ports:
            - "14432:5432"
volumes:
    pgsql_data:
