version: '3'

services:
    php-fpm:
        build:
            context: .  # Chemin du contexte de build
            dockerfile: Dockerfile  # Chemin du Dockerfile
        volumes:
            - ./:/var/www/html  # Utilisation du chemin absolu du répertoire racine du projet
        networks:
            - laravel-network

    nginx:
        image: nginx:latest
        ports:
            - "14200:80"
        volumes:
            - ./nginx/config.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html  # Utilisation du chemin absolu du répertoire racine du projet
        depends_on:
            - php-fpm
        networks:
            - laravel-network

    postgresql:
        image: postgres:latest
        container_name: laravel_postgresql
        ports:
            - "14432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: arnoldetmaX291
            POSTGRES_DB: Crud
        volumes:
            - postgresql_data:/var/lib/postgresql/data
        networks:
            - laravel-network

volumes:
    postgresql_data:

networks:
    laravel-network:
        driver: bridge
